version: '3.8'

services: # define services(containers) to be run
  user-service: # name of the service
    build: # build the image using the Dockerfile in the specified context
      context: . # path to the directory containing the Dockerfile
      dockerfile: ./services/user-service/Dockerfile # name of the Dockerfile
    ports:
      - "8080:8080" # map port 8080 of the container to port 8080 on the host
    env_file:
      - ./services/user-service/.env 
    depends_on:
      db:
        condition: service_healthy # ensure the db service is started before this one
    environment:
      - GIN_MODE=debug # set environment variable for Gin framework
  wallet-service:
    build:
      context: .
      dockerfile: ./services/wallet-service/Dockerfile
    ports:
      - "8081:8081"
      - "50052:50052"
    env_file:
      - ./services/wallet-service/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GIN_MODE=debug
  transaction-service:
    build:
      context: .
      dockerfile: ./services/transaction-service/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./services/transaction-service/.env
    depends_on:
      db:
        condition: service_healthy
      wallet-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - GIN_MODE=debug
  notification-service:
    build:
      context: .
      dockerfile: ./services/notification-service/Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./services/notification-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - GIN_MODE=debug
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ./services/frontend/.env.local
    ports:
      - "3000:3000" # map port 3000 of the container to port 3000 on the host
    volumes:
      - ./services/frontend:/app
      - /app/node_modules # avoid overwriting node_modules in the container
    depends_on:
      - user-service # ensure the user-service is started before this one
      - wallet-service
      - transaction-service
      - notification-service
  db:
    image: postgres:14-alpine # use the official PostgreSQL image
    ports: # map the database port
      - "5432:5432" # map port 5432 of the container to port 5432 on the host
    volumes: 
      - postgres_data:/var/lib/postgresql/data # Persist database data
    environment:
      - POSTGRES_USER=user # database username
      - POSTGRES_PASSWORD=password # database password
      - POSTGRES_DB=gop2pwallet # database name
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gop2pwallet"]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672" # for amqp (the protocol)
      - "15672:15672" # for management web ui (http://localhost:15672/)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics","check_running"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      

volumes:
  postgres_data: # define a named volume for PostgreSQL data persistence
  rabbitmq_data: # define a named volume for RabbitMQ data persistence