worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    upstream users {
        server user-service:8080;
    }
    upstream wallets {
        server wallet-service:8081;
    }
    upstream transactions {
        server transaction-service:8082;
    }
    upstream notifications {
        server notification-service:8083;
    }

    server {
        listen 80;
        
         # --- CORS CONFIGURATION ---
        # Allow requests from anywhere (since Vercel proxies, it comes from one place)
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Upgrade,Connection' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;

        # Handle Preflight requests (OPTIONS)
        if ($request_method = 'OPTIONS') {
            return 204;
        }

        location /api/v1/auth {
            proxy_pass http://users;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/users {
            proxy_pass http://users;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/wallet {
            proxy_pass http://wallets;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/transactions {
            proxy_pass http://transactions;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /ws {
            proxy_pass http://notifications;

            # Force the protocol version
            proxy_http_version 1.1;

            # HARDCODE these headers so they are never missing
            proxy_set_header Upgrade "websocket";
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_buffering off;
            proxy_cache off;
            
            # Increase timeouts so connections don't drop
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
        }
        
        # Note: We removed the 'location /' block because Nginx is 
        # NOT serving the frontend files anymore. Vercel does that.
    }
}